---
title: "R Notebook"
output: html_notebook
---
```{r}
HRSdataDir <- "C:/Users/Bri/Documents/grad-repo/grad-repo/SRP/"
load(paste0(HRSdataDir,"PGENSCORE3A_R.RData")) #AA PGS
load(paste0(HRSdataDir, "PGENSCORE3E_R.RData")) #European PGS
load(paste0(HRSdataDir, "TRK2016TR_R.RData")) #tracker file

load(paste0(HRSdataDir, "H10PR.RData")) #2010 CORE preload questions
load(paste0(HRSdataDir, "H10LB.RData")) #2010 CORE leave behind questionaire

load(paste0(HRSdataDir, "H12PR.RData")) #2012 CORE preload questions
load(paste0(HRSdataDir, "H12LB.RData")) #2012 CORE leave behind questionaire

H10I_R <- read_sav("H10I_R.sav")
H12I_R <- read_sav("H12I_R.sav")
```

```{r}
### ADD GROUP VARIABLE TO PGEN EA AND AA FILES
PGENSCORE3A_R$group = rep("AA",nrow(PGENSCORE3A_R))
PGENSCORE3E_R$group = rep("EA",nrow(PGENSCORE3E_R))

### MAKE SINGLE VARIABLE ID: CONCATENATE(HHID,PN)
PGENSCORE3A_R$HHID_PN = paste0(PGENSCORE3A_R$HHID,PGENSCORE3A_R$PN)
PGENSCORE3E_R$HHID_PN = paste0(PGENSCORE3E_R$HHID,PGENSCORE3E_R$PN)
TRK2016TR_R$HHID_PN = paste0(TRK2016TR_R$HHID,TRK2016TR_R$PN)

### MAKE CONSISTENT COLNAMES IN EA AND AA FILES
### edited these manually in text editor (separately AA & EA just in case variables in different order), worth a double check
colnames(PGENSCORE3A_R) = c("HHID", "PN", "PC1_5A", "PC1_5B", "PC1_5C", "PC1_5D", "PC1_5E", "PC6_10A", "PC6_10B", "PC6_10C", "PC6_10D", "PC6_10E", "PGS3_GENCOG_CHRG15", "PGS3_BMI_GIANT15", "PGS3_HEIGHT_GIANT14", "PGS3_SCZ_PGC14", "PGS3_EDU2_SSGAC16", "PGS3_EVRSMK_TAG10", "PGS3_AD_IGAP13", "PGS3_AD2_IGAP13", "PGS3_WC_GIANT15", "PGS3_WHR_GIANT15", "PGS3_NEURO_SSGAC16", "PGS3_WELLB_SSGAC16", "PGS3_DPSYMP_SSGAC16", "PGS3_CAD_CARDIOGR11", "PGS3_MI_CARDIOGR15", "PGS3_CRTSL_CORNET14", "PGS3_T2D_DIAGRAM12", "PGS3_BIP_PGC11", "PGS3_ADHD_PGC17", "PGS3_ADHD_PGC10", "PGS3_XDISORDERPGC13", "PGS3_MENARCHE_RPG14", "PGS3_MENOPAUS_RPG15", "PGS3_MDD_PGC13", "PGS3_CPD_TAG10", "PGS3_EXTRAV_GPC17", "PGS3_AUTISM_PGC17", "PGS3_LNGVTY_CHARG15", "PGS3_AB_BROAD17", "PGS3_EDU3_SSGAC18", "PGS3_OCD_IOCDF17", "PGS3_AFBC_SOCGEN16", "PGS3_AFBF_SOCGEN16", "PGS3_AFBM_SOCGEN16", "PGS3_NEBC_SOCGEN16", "PGS3_NEBF_SOCGEN16", "PGS3_NEBM_SOCGEN16", "PGS3_MDD2_PGC18", "PGS3_PTSDAA_PGC18", "PGS3_PTSDEA_PGC18", "PGS3_PTSDC_PGC18", "PGS3_HDL_GLGC13", "PGS3_LDL_GLGC13", "PGS3_TC_GLGC13", "PGS3_ANXFS_ANGST16", "PGS3_ANXCC_ANGST16", "VERSION", "group", "HHID_PN")
colnames(PGENSCORE3E_R) = c("HHID", "PN", "PC1_5A", "PC1_5B", "PC1_5C", "PC1_5D", "PC1_5E", "PC6_10A", "PC6_10B", "PC6_10C", "PC6_10D", "PC6_10E", "PGS3_GENCOG_CHRG15", "PGS3_BMI_GIANT15", "PGS3_HEIGHT_GIANT14", "PGS3_SCZ_PGC14", "PGS3_EDU2_SSGAC16", "PGS3_EVRSMK_TAG10", "PGS3_AD_IGAP13", "PGS3_AD2_IGAP13", "PGS3_WC_GIANT15", "PGS3_WHR_GIANT15", "PGS3_NEURO_SSGAC16", "PGS3_WELLB_SSGAC16", "PGS3_DPSYMP_SSGAC16", "PGS3_CAD_CARDIOGR11", "PGS3_MI_CARDIOGR15", "PGS3_CRTSL_CORNET14", "PGS3_T2D_DIAGRAM12", "PGS3_BIP_PGC11", "PGS3_ADHD_PGC17", "PGS3_ADHD_PGC10", "PGS3_XDISORDERPGC13", "PGS3_MENARCHE_RPG14", "PGS3_MENOPAUS_RPG15", "PGS3_MDD_PGC13", "PGS3_CPD_TAG10", "PGS3_EXTRAV_GPC17", "PGS3_AUTISM_PGC17", "PGS3_LNGVTY_CHARG15", "PGS3_AB_BROAD17", "PGS3_EDU3_SSGAC18", "PGS3_OCD_IOCDF17", "PGS3_AFBC_SOCGEN16", "PGS3_AFBF_SOCGEN16", "PGS3_AFBM_SOCGEN16", "PGS3_NEBC_SOCGEN16", "PGS3_NEBF_SOCGEN16", "PGS3_NEBM_SOCGEN16", "PGS3_MDD2_PGC18", "PGS3_PTSDAA_PGC18", "PGS3_PTSDEA_PGC18", "PGS3_PTSDC_PGC18", "PGS3_HDL_GLGC13", "PGS3_LDL_GLGC13", "PGS3_TC_GLGC13", "PGS3_ANXFS_ANGST16", "PGS3_ANXCC_ANGST16", "VERSION", "group", "HHID_PN")

### MERGE AA & EA PGS FILES
### before merge, AA N = 3100, EA N = 12090
PGENSCORE3 = merge(PGENSCORE3A_R,PGENSCORE3E_R, all=T)
### post-merge PGS N = 15190

### MERGE PGS WITH TRACKER FILE

### all participants, even those without genotypes
PGENSCORE3_TRK2016TR_ALL = merge(TRK2016TR_R,PGENSCORE3,all=T)

### only participants with genotypes
PGENSCORE3_TRK2016TR_ONLY_PGS = merge(TRK2016TR_R,PGENSCORE3)

### remember to split analyses by group (AA or EA)
```

```{r}
library(dplyr)
SRP_DATASET = select(PGENSCORE3_TRK2016TR_ONLY_PGS, HHID, PN, HHID_PN, BIRTHYR, GENDER, RACE, EFTFASSIGN)
SRP_DATASET$LBY = paste0(SRP_DATASET$HHID_PN,SRP_DATASET$EFTFASSIGN)
```

```{r}
H10LB_1 = as.data.frame(H10LB)
H10LB_1$EFTFASSIGN =(rep(1,nrow(H10LB_1)))
H10LB_1$HHID_PN = paste0(H10LB_1$HHID,H10LB_1$PN)
H10LB_1$LBY = paste0(H10LB_1$HHID_PN, H10LB_1$EFTFASSIGN)
#H10LB_1$YEAR = (rep(2010,nrow(H10LB_1)))
```


```{r}
H12LB_1 = as.data.frame(H12LB)
H12LB_1$EFTFASSIGN = (rep(2,nrow(H12LB_1)))
H12LB_1$HHID_PN = paste0(H12LB_1$HHID,H12LB_1$PN)
H12LB_1$LBY = paste0(H12LB_1$HHID_PN, H12LB_1$EFTFASSIGN)
#H10LB_1$YEAR= (rep(2012,nrow(H10LB_1)))
```

```{r}
names(H10LB_1) = substring(names(H10LB_1),2)
colnames(H10LB_1)[1] <- "HHID" 
colnames(H10LB_1)[2] <- "PN"
colnames(H10LB_1)[403] <- "HHID_PN" 
colnames(H10LB_1)[404] <- "LBY"
H10LB_1 = H10LB_1[-c(402)]
```



```{r}
names(H12LB_1) = substring(names(H12LB_1),2)
colnames(H12LB_1)[1] <- "HHID" 
colnames(H12LB_1)[2] <- "PN"
colnames(H12LB_1)[487] <- "HHID_PN" 
colnames(H12LB_1)[488] <- "LBY" 
H12LB_1 = H12LB_1[-c(486)]
```

```{r}
H10LB_1 = H10LB_1[-c(222:245,348:365,372:398)]
H12LB_1 = H12LB_1[-c(241:243,327:334,341:346,348:483)]
```

```{r}
H12LB_1 = filter(H12LB_1, LBCOMP<5)
H10LB_1 = filter(H10LB_1, LBCOMP<5)
```

```{r}
H10LB_1$YEAR = (rep(2010,nrow(H10LB_1)))
H12LB_1$YEAR = (rep(2012,nrow(H12LB_1)))
HLB = bind_rows(H10LB_1,H12LB_1)
```

```{r}
#SRP_DATASET_PGSA = 
SRP_DATASET_FINAL = left_join(SRP_DATASET,HLB, by="LBY")
```

```{r}
SRP_DATASET_FINAL = filter(SRP_DATASET_FINAL, LBCOMP<5)
EDU = dplyr::select(PGENSCORE3_TRK2016TR_ONLY_PGS,HHID_PN,DEGREE)
```

```{r}
ID = select(SRP_DATASET_FINAL, HHID_PN.x)
colnames(ID) = c("HHID_PN")
EDU = inner_join(EDU,ID,by="HHID_PN")
EDU = dplyr:: select(EDU,-HHID_PN)
```

PGS
```{r}
SRP_DATASET_PGS_A = inner_join(PGENSCORE3,ID, by = "HHID_PN")
```

```{r}
Height10<- H10I_R [c(1,2,134)]
Height10$HHID_PN = paste0(Height10$HHID,Height10$PN)
Height12 <- H12I_R[c(1,2,134)]
Height12$HHID_PN = paste0(Height12$HHID,Height12$PN)

colnames(Height10)[3] <- "Height"
colnames(Height12)[3] <- "Height"

Height10$LBY <- paste0(Height10$HHID_PN,"1")
Height12$LBY <-paste0(Height12$HHID_PN,"2")

Height <- bind_rows(Height10,Height12)

Height_final <- left_join(SRP_DATASET_FINAL,Height, by="LBY")
```

